# -*- coding: utf-8 -*-
"""supun_py_lec_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125ZUipmxTLYKBg7wo2DlceoSTlpqRA4w
"""



class FactorialHelper:

  def __init__(self):
    self.number = 0
    self.factorial = 1

  def get_input(self):
    self.number = int(input('Please enter a number to calculate factorial : '))

  def calculate(self):
    for i in range(self.number):
      self.factorial = self.factorial * (self.number-i)
    return self.factorial

  def print_factorial(self):
    print('factorial ' + str(self.number) +  ' = ' + str(self.factorial))

factorialHelper = FactorialHelper()
factorialHelper.get_input()
factorialHelper.calculate()
factorialHelper.print_factorial()