# -*- coding: utf-8 -*-
"""supun_py_lec_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125ZUipmxTLYKBg7wo2DlceoSTlpqRA4w
"""



class FactorialHelper:

  def __init__(self):
    self.number = 0
    self.factorial = 1
    self.is_prime = False

  def get_input(self):
    self.number = int(input('Please enter a number to calculate factorial : '))

  def calculate(self):
    for i in range(self.number):
      self.factorial = self.factorial * (self.number-i)
    print('factorial ' + str(self.number) +  ' = ' + str(self.factorial))

  def check_prime(self):
    if(self.factorial <= 1):
      self.is_prime = False

    for i in range(2, int(self.factorial**0.5) , 1):
      if(i%2 == 0):
        self.is_prime = False
        break
    self.is_prime = True

    if(self.is_prime):
      print('factorial ' + str(self.factorial) +  ' is a prime number')
    else:
      print('factorial ' + str(self.factorial) +  ' is not a prime number')



factorialHelper = FactorialHelper()
factorialHelper.get_input()
factorialHelper.calculate()
factorialHelper.check_prime()