# -*- coding: utf-8 -*-
"""supun_py_lec_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125ZUipmxTLYKBg7wo2DlceoSTlpqRA4w
"""



def area(l,w):
  area_land = l*w
  return area_land

ans = area(3.5,10.88)



ans = round(ans)


def calFactorial(x):
  factorial = 1
  for i in range(x):
    factorial = factorial * (x-i)
  return factorial

def printFactorial(n,f):
  print('factorial ' + str(n) +  ' = ' + str(f))

f5 = calFactorial(5)
printFactorial(5,f5)


f4 = calFactorial(4)
printFactorial(4,f4)